#!/bin/bash

# Description: Link dotfiles to home directory

mkdir -p ~/.config

ln -sf ~/dotfiles-devpod/bashrc ~/.bashrc
ln -sf ~/dotfiles-devpod/starship.toml ~/.config/startship.toml

echo "Dotfiles linked!"
